[project]
name = "scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.12.0",
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.8",
    "nnterp>=1.2.2",
    "scipy>=1.17.0",
    "transformers>=5.0.0",
]
